#!/usr/bin/env perl

use v5.14;
use warnings;
use App::diff2vba;

App::diff2vba->new->run(splice @ARGV);

exit;

__END__

=encoding utf-8

=head1 NAME

diff2vba - generate VBA patch script from diff output

=head1 VERSION

Version 0.06

=head1 SYNOPSIS

greple -Mmsdoc -Msubst \
    --all-sample-dict --diff some.docx | diff2vba > patch.vba

=head1 DESCRIPTION

B<diff2vba> is a command to generate VBA patch script from diff output.

=head1 OPTIONS

=over 7

=item B<--maxlen>=I<n>

Set maximum length of literal string.
Default is 250.

=begin comment

=item B<--format>=I<format>

Set format of VBA script.
Default is C<dumb>.

=end comment

=item B<--subname>=I<name>

Set subroutine name in the VBA script.
Default is C<Patch>.

=item B<--identical>

Produce patch script for identical string.
Default is false.

=back

=head1 INSTALL

cpanm https://github.com/kaz-utashiro/App-diff2vba.git

=head1 SEE ALSO

L<App::Greple>, L<https://github.com/kaz-utashiro/greple>

L<App::Greple::msdoc>, L<https://github.com/kaz-utashiro/greple-msdoc>

L<App::Greple::subst>, L<https://github.com/kaz-utashiro/greple-subst>

L<https://qiita.com/kaz-utashiro/items/85add653a71a7e01c415>

=head1 AUTHOR

Kazumasa Utashiro

=head1 LICENSE

Copyright 2021 Kazumasa Utashiro.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
