#!/usr/bin/env perl

use v5.14;
use warnings;
use App::diff2vba;

App::diff2vba->new->run(splice @ARGV);

exit;

__END__

=encoding utf-8

=head1 NAME

diff2vba - generate VBA patch script from diff output

=head1 VERSION

Version 0.02

=head1 SYNOPSIS

greple -Msubst --diff old.docx new.docx | diff2vba > patch.vba

=head1 DESCRIPTION

B<diff2vba> is a command to generate VBA patch script from diff output.

=head1 OPTIONS

=over 7

=item B<--fold>[=I<width>]

Fold VBA string literals.  Default true with 72 column width.
Specify 0 not to fold.

=item B<--variable>[=I<name>]

Specify VBA array variable name.  Default is C<subst>.

=back

=head1 INSTALL

cpanm https://github.com/kaz-utashiro/App-diff2vba.git

=head1 SEE ALSO

L<App::Greple>, L<https://github.com/kaz-utashiro/greple>

L<App::Greple::subst>, L<https://github.com/kaz-utashiro/greple-subst>

L<https://qiita.com/kaz-utashiro/items/85add653a71a7e01c415>

=head1 AUTHOR

Kazumasa Utashiro

=head1 LICENSE

Copyright 2021 Kazumasa Utashiro.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
